// LOCALHOST

### Get ALL contacts
GET http://localhost:3003/users

### Get contact by ID
GET http://localhost:3003/users/67d0aadbc3264cef2aef4844

### Create a new contact
POST http://localhost:3003/users
Content-Type: application/json

{
  "email": "test5@example.com",
  "username": "test5@test.com",
  "name": "Hello4",
  "ipaddress": "194.121.163.63"
}

### PUT contact
PUT http://localhost:3003/users/67d17bb002f784bad2253b13
Content-Type: application/json

{
  "email": "test5@example.com",
  "username": "test5@test.com",
  "name": "Hello4",
  "ipaddress": "194.121.163.63"
}

### Delete contact
DELETE http://localhost:3003/users/67d17bb002f784bad2253b13